# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtCNlhujDVkCHTH7ZWO92xHSfUXZxUxU
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pickle
import gradio as gr
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import io


from google.colab import drive
drive.mount('/content/drive')
print(" Google Drive Mounted Successfully!")

FILE_PATH = '/content/drive/MyDrive/'
MODEL_FILE = FILE_PATH + 'flight_delay_model.pkl'
ENCODERS_FILE = FILE_PATH + 'flight_encoders.pkl'
DATA_FILE = FILE_PATH + 'cleaned_flight_data.csv'

OPERATING_AIRLINE_COL = 'Operating_Airline '
DELAY_MINUTES_COL = 'DepDelayMinutes'
TIME_COL = 'CRSDepTime'
DATE_COL = 'FlightDate'

try:
    with open(MODEL_FILE, 'rb') as file:
        model = pickle.load(file)
    with open(ENCODERS_FILE, 'rb') as file:
        encoders = pickle.load(file)
    print(" Model and Encoders loaded.")

    df_temp = pd.read_csv(DATA_FILE, usecols=[OPERATING_AIRLINE_COL, 'Origin', 'Dest', TIME_COL, DATE_COL, DELAY_MINUTES_COL])


    print(" Raw Data loaded for list generation.")

except Exception as e:
    print(f" FATAL ERROR loading files or data: {e}")

    raise e




def time_to_min(time_val):
    if pd.isna(time_val):
        return np.nan
    try:
        time_str = str(int(time_val)).zfill(4)
        hour = int(time_str[:2])
        minute = int(time_str[2:])
        return hour * 60 + minute
    except ValueError:
        return np.nan


df_temp['SCHED_DEP_MIN'] = df_temp[TIME_COL].apply(time_to_min)
df_temp['IS_DELAYED'] = (df_temp[DELAY_MINUTES_COL] > 15).astype(int)


Airlines = sorted(df_temp[OPERATING_AIRLINE_COL].dropna().unique().tolist())
Airports = sorted(list(set(df_temp['Origin'].dropna().unique()) | set(df_temp['Dest'].dropna().unique())))

print(" Lists for Dropdowns created successfully.")

def time_to_min_gradio(time_obj):
    if not time_obj:
        return np.nan
    try:

        time_parts = str(time_obj).split(':')
        hour = int(time_parts[0])
        minute = int(time_parts[1])
        return hour * 60 + minute
    except:
        return np.nan


def predict_delay(input_data):

    input_df = pd.DataFrame([input_data])


    for col, le in encoders.items():
        try:
            input_df[col] = le.transform(input_df[col].astype(str))
        except ValueError:

            input_df[col] = len(le.classes_)

    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)[:, 1]

    return prediction[0], probability[0]

# Gradio ke liye Wrapper function
def predict_flight_delay(date_str, time_str, airline, origin, destination):

    try:
        fl_date = pd.to_datetime(date_str)
    except:
        return "Error: Invalid Date Format (Use YYYY-MM-DD)"

    fl_time_min = time_to_min_gradio(time_str)

    input_data = {
        'MONTH': fl_date.month,
        'DAY_OF_WEEK': fl_date.dayofweek,
        'SCHED_DEP_MIN': fl_time_min,
        OPERATING_AIRLINE_COL: airline,
        'Origin': origin,
        'Dest': destination
    }

    prediction, probability = predict_delay(input_data)

    prob_percent = probability * 100

    if prediction == 1:
        return f" HIGH RISK OF DELAY (15+ mins)! Probability: {prob_percent:.2f}%"
    else:
        return f" LIKELY ON-TIME! Probability: {(100 - prob_percent):.2f}%"

# Colab Cell 3: Gradio Interface Launch (FINAL DESIGN - With Background Image)

# NOTE: Aapko Block 1 aur Block 2 ke saare variables (df_temp, Airlines, etc.) load karne honge.

# --- Custom CSS for High Contrast and Visual Impact with Background Image ---
# Colab Cell 3: CUSTOM_CSS Update

# --- Custom CSS for High Contrast and Visual Impact with Background Image ---
CUSTOM_CSS = """
/* Global Background with Image */
body {
    /* !important tag se hum browser ko force karte hain ki yeh style apply ho */
    background-image: url('https://i.imgur.com/B9M9x7t.jpeg') !important;
    background-size: cover !important;
    background-position: center !important;
    background-repeat: no-repeat !important;
    background-attachment: fixed !important;
    background-color: #f0f2f5 !important;
}
/* Main Container/Card (White) */
.gradio-container {
    /* White with 90% opacity for text readability */
    background-color: rgba(255, 255, 255, 0.9) !important;
    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);
    border-radius: 15px;
    margin: 30px auto;
    max-width: 900px;
}
/* Title Styling */
h1 {
    color: #2c3e50 !important;
    text-align: center !important;
    font-size: 2.8em !important;
    font-weight: 800 !important;
    text-shadow: 1px 1px 3px rgba(0,0,0,0.2);
    padding-top: 20px;
}
/* Info Panel */
#info_box {
    background-color: #ecf0f1;
    border-left: 5px solid #3498db;
    padding: 15px;
    border-radius: 8px;
}
/* Input panels */
.panel {
    border: 1px solid #dcdfe6;
    border-radius: 10px;
    padding: 15px;
    background-color: #ffffff;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
}
"""
# Baaki saare functions aur iface.launch() ka code same rahega.
PROJECT_DESCRIPTION = """
<div style="text-align: center; margin-bottom: 20px; padding: 15px; border-radius: 10px; background-color: #ffffff; border-bottom: 2px solid #34495e;">
    <h3 style="color: #34495e;">✈️ **Flight Delay Predictor: Powered by XGBoost ML** ✈️</h3>
    <p style="color: #7f8c8d;">
        Analyze historical data for **Airline, Route, and Time of Day** to predict flight punctuality.
        **Enter flight details below for an instant risk assessment.**
    </p>
</div>
"""

# --- Visualization Function (Same as previous fix, just included for completeness) ---
def generate_time_of_day_delay_plot():
    bins = [0, 360, 720, 1080, 1440]
    labels = ['Night (12am-6am)', 'Morning (6am-12pm)', 'Afternoon (12pm-6pm)', 'Evening (6pm-12am)']

    df_temp['TIME_BLOCK'] = pd.cut(df_temp['SCHED_DEP_MIN'], bins=bins, labels=labels, right=False)
    delay_by_time = df_temp.groupby('TIME_BLOCK')[DELAY_MINUTES_COL].mean().reindex(labels)

    fig = plt.figure(figsize=(10, 6))
    sns.barplot(x=delay_by_time.index, y=delay_by_time.values, palette="rocket", hue=delay_by_time.index, legend=False)

    plt.title('Average Flight Delay by Time of Day', fontsize=14)
    plt.ylabel('Average Delay (Minutes)', fontsize=12)
    plt.xlabel('Time Block', fontsize=12)
    plt.xticks(rotation=15, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    return fig


# --- Prediction Logic Wrapper Fix for Dynamic Output Color ---
def predict_flight_delay_styled(date_str, time_str, airline, origin, destination):
    result_text = predict_flight_delay(date_str, time_str, airline, origin, destination)

    if result_text.startswith('❌'):
        style = "background-color: #f7a8a8; color: #c0392b; border: 2px solid #e74c3c;"
    else:
        style = "background-color: #b2f5b2; color: #27ae60; border: 2px solid #2ecc71;"

    return f'<div id="prediction-result" style="{style}">{result_text}</div>'


# --- Gradio Interface Logic ---

with gr.Blocks(theme=gr.themes.Soft(), css=CUSTOM_CSS) as iface:

    gr.HTML(PROJECT_DESCRIPTION)

    with gr.Tab("🚀 Delay Prediction"):
        gr.Markdown("## **Enter Flight Details**")

        with gr.Row():
            with gr.Column(scale=1, elem_classes="panel"): # Input ko ek chota panel look denge
                gr.Markdown("**📅 Time & Date**")
                date_input = gr.Textbox(label="1. Scheduled Date (YYYY-MM-DD)", value=str(datetime.now().date()))
                time_input = gr.Textbox(label="2. Scheduled Time (HH:MM)", value=str(datetime.now().strftime('%H:%MM'))) # Changed default format

            with gr.Column(scale=2, elem_classes="panel"):
                gr.Markdown("**✈️ Route & Carrier**")
                airline_input = gr.Dropdown(choices=Airlines, label="3. Airline (Carrier)")
                origin_input = gr.Dropdown(choices=Airports, label="4. Departure Airport (ORIGIN)")
                dest_input = gr.Dropdown(choices=Airports, label="5. Arrival Airport (DESTINATION)")

        predict_btn = gr.Button("🔮 Predict Delay Now", variant="primary", scale=1)
        prediction_output_html = gr.HTML(label="Prediction Result", value="<div id='prediction-result'>Enter details and click 'Predict'</div>", show_label=False)

        gr.HTML("""
        <div id='info_box'>
            <h5>📊 **Model Insights**</h5>
            <p>• Accuracy: **~78.55%** | Model: **XGBoost Classifier**.</p>
            <p>• Features: **Time, Day, Month, Carrier, Origin, Destination**.</p>
        </div>
        """)

        predict_btn.click(
            fn=predict_flight_delay_styled,
            inputs=[date_input, time_input, airline_input, origin_input, dest_input],
            outputs=prediction_output_html
        )

    with gr.Tab("📈 Historical Analysis"):
        gr.Markdown("## **Visual Insights: Delay Trends**")

        gr.Plot(generate_time_of_day_delay_plot, label="Average Delay by Time Block")

        gr.HTML("""
        <div style="padding: 10px; background-color: #fcf8e3; border-radius: 8px; border: 1px solid #f9e1ad;">
            <p>🎯 **Key Finding:** As shown in the chart, delays tend to be lowest in the **Morning (6am-12pm)** and highest in the **Evening (6pm-12am)** due to cascade effects.</p>
        </div>
        """)

# App ko launch karna
iface.launch(share=True)